name: Deploy Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      # Pull env from Vercel (creates .vercel and .env.* if configured there)
      - name: Pull Vercel env
        run: npx vercel pull --yes --environment=preview --token=${{ env.VERCEL_TOKEN }}

      - name: Build (prebuilt artifacts)
        run: npx vercel build --token=${{ env.VERCEL_TOKEN }}

      - name: Deploy preview
        id: deploy
        run: |
          URL=$(npx vercel deploy --prebuilt --token=${{ env.VERCEL_TOKEN }})
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Comment preview URL on PR
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: "🟢 Preview deployed: ${{ steps.deploy.outputs.url }}"
