name: Pre-Vercel Sanity Check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  sanity:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure single lockfile (npm only)
        run: |
          if [ -f yarn.lock ] || [ -f pnpm-lock.yaml ]; then
            echo "::error::Found multiple lockfiles. Keep only package-lock.json for npm builds."
            ls -la | sed -n '1,120p'
            exit 1
          fi
          if [ ! -f package-lock.json ]; then
            echo "::error::package-lock.json missing. Run 'npm install' locally and commit the lockfile."
            exit 1
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Clean install (uses lockfile)
        run: npm ci

      - name: Verify critical deps resolve (@supabase/ssr, next, react)
        run: |
          node -e "const deps=require('./package.json').dependencies||{}; const want=['@supabase/ssr','@supabase/supabase-js','next','react','react-dom']; let fail=0; for (const pkg of want) { if (deps[pkg]) { try { require.resolve(pkg); console.log('OK:', pkg); } catch(e) { console.log('MISSING:', pkg); fail=1; } } else { console.log('SKIP (not in deps):', pkg); } } process.exit(fail);"

      - name: Show top-level dependency tree (for debugging)
        run: npm ls --depth=0 || true

      # Optional: do a quick type/lint/build dry‑run (kept separate from your main CI)
      - name: Build (no export) to mimic Vercel build
        run: npm run build --if-present